version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    networks:
      - app_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    command: exit
