# Generated by Django 5.1.3 on 2024-11-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_user_nickname_user_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="roles",
            new_name="role",
        ),
    ]
