# Generated by Django 5.1.3 on 2024-11-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_rename_roles_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("A", "ADMIN"), ("S", "STAFF"), ("U", "USER")],
                default="U",
                max_length=1,
            ),
        ),
    ]
